// Package sdr — HackRF One RX driver (real libhackrf bindings).
//
// Build: go build -tags hackrf ./cmd/sdr-capture   (requires libhackrf)
// macOS: brew install hackrf · Debian/Ubuntu: apt install libhackrf-dev
//
// Policy: RX-only — H2 (SPEC §1.2, §15.4). The driver reports
// HasTX=false and the libhackrf transmit API (hackrf_start_tx) is
// intentionally never referenced; internal/sdr/hackrf_test.go enforces
// that at test time.
//
// Binding notes (verified against hackrf.h, libhackrf 2026.01):
//   - HackRF delivers signed 8-bit I/Q samples; each is widened to a
//     full-scale int16 (v << 8) so downstream keeps dividing by 32768,
//     the same convention as the RTL driver (§15.3).
//   - RX is asynchronous (callback driven), but the sdr.SDR interface
//     is synchronous. The callback converts into block buffers that
//     ReadIQ drains through a small queue; on queue overflow the
//     freshest block is dropped and counted. Retunes flush the queue
//     so the pipeline mostly sees post-retune samples (§7.1).
//go:build hackrf

package sdr

/*
#cgo pkg-config: libhackrf
#include <stdlib.h>
#include <hackrf.h>

// The //export'd RX callback is declared here so C.hackrfRXCallback
// resolves from Go; the definition is generated by cgo. (Declarations
// only — the //export preamble restriction forbids definitions.)
extern int hackrfRXCallback(hackrf_transfer* transfer);
*/
import "C"

import (
	"fmt"
	"log"
	"sync"
	"sync/atomic"
	"time"
	"unsafe"
)

const (
	// hackRFBlockSamples is the block granularity between the RX
	// callback and ReadIQ, in int16 slots. 131072 slots = 65536 I/Q
	// pairs = libhackrf's default 262144-byte transfer.
	hackRFBlockSamples = 1 << 17

	// hackRFBlockQueue bounds in-flight converted blocks. Four blocks
	// ≈ 109 ms at 2.4 MSPS, 13 ms at 20 MSPS — short enough that
	// scan-loop retunes stay meaningful (§7.1).
	hackRFBlockQueue = 4

	// hackRFReadTimeout is how long ReadIQ waits for the callback to
	// deliver data before surfacing a stall (e.g. unplugged device).
	hackRFReadTimeout = 2 * time.Second
)

// HackRF implements the SDR interface for HackRF hardware. RX-only
// (H2): there is no transmit path anywhere in this driver.
//
// Concurrency: the libhackrf callback runs on a C thread and only
// touches the block channels and atomics — never mu. blk/pos state is
// owned by the single ReadIQ caller (the per-slot IQ read loop),
// mirroring how the RTL driver's sync read is used.
type HackRF struct {
	id     string
	serial string // configured serial ("" = first device found)
	meta   SDRMetadata

	mu      sync.Mutex // guards dev/started/closed
	dev     *C.hackrf_device
	started bool
	closed  bool

	ready   chan []int16  // converted blocks awaiting ReadIQ
	idle    chan []int16  // recycled block buffers
	blk     []int16       // block partially consumed by ReadIQ (single reader)
	pos     int           // read cursor into blk (single reader)
	done    chan struct{} // closed by Close to wake a blocked ReadIQ
	dropped atomic.Int64  // I/Q pairs dropped on queue overflow
	dead    atomic.Bool   // set by the callback on USB/transfer failure

	loggedDrops atomic.Int64 // last drop count reported by ReadIQ
}

// hackrfOwners maps an open hackrf_device back to its Go driver so the
// C callback can dispatch without relying on rx_ctx plumbing.
var hackrfOwners sync.Map // *C.hackrf_device -> *HackRF

// compile-time interface check.
var _ SDR = (*HackRF)(nil)

// NewHackRF initializes libhackrf and validates the configured serial
// against the connected devices without opening one (Open does that).
// An empty serial selects the first device found.
func NewHackRF(id string, serial string) (*HackRF, error) {
	if rc := C.hackrf_init(); rc != C.HACKRF_SUCCESS {
		return nil, fmt.Errorf("hackrf: init failed: %s", hackrfStrerr(int(rc)))
	}
	list := C.hackrf_device_list()
	if list == nil {
		return nil, fmt.Errorf("hackrf: device list failed")
	}
	defer C.hackrf_device_list_free(list)

	n := int(list.devicecount)
	if n == 0 {
		return nil, fmt.Errorf("hackrf: no HackRF devices found")
	}
	// cgo exposes the list's char**/enum* fields as opaque pointers;
	// view them through bounded arrays (devicecount >= 1 here).
	serials := (*[1 << 12]*C.char)(unsafe.Pointer(list.serial_numbers))[:n:n]
	boards := (*[1 << 12]C.uint32_t)(unsafe.Pointer(list.usb_board_ids))[:n:n]

	idx := 0
	if serial != "" {
		found := false
		for i := 0; i < n; i++ {
			if C.GoString(serials[i]) == serial {
				idx, found = i, true
				break
			}
		}
		if !found {
			return nil, fmt.Errorf("hackrf: no device with serial %q (%d device(s) connected)", serial, n)
		}
	}

	model := "HackRF One"
	if name := C.hackrf_usb_board_id_name(
		C.enum_hackrf_usb_board_id(boards[idx])); name != nil {
		if s := C.GoString(name); s != "" {
			model = s
		}
	}
	listSerial := ""
	if serials[idx] != nil {
		listSerial = C.GoString(serials[idx])
	}

	// H1: 1 MHz - 7250 MHz. MaxBW is the practical ~20 MSPS cap
	// (§15.2); SetSampleRate clamps requests to it. H2: HasTX false.
	return &HackRF{
		id:     id,
		serial: serial,
		meta: SDRMetadata{
			ID:      id,
			Model:   model,
			Serial:  listSerial,
			FreqMin: 1_000_000,
			FreqMax: 7_250_000_000,
			MaxBW:   20_000_000,
			HasTX:   false,
		},
		ready: make(chan []int16, hackRFBlockQueue),
		idle:  make(chan []int16, hackRFBlockQueue),
		done:  make(chan struct{}),
	}, nil
}

// Open claims the device. The 14 dB amp is disabled so the gain chain
// is LNA+VGA only and deterministic (§5.6 calibration prerequisite).
func (h *HackRF) Open() error {
	h.mu.Lock()
	defer h.mu.Unlock()
	if h.closed {
		return fmt.Errorf("hackrf: device closed")
	}
	if h.dev != nil {
		return fmt.Errorf("hackrf: device already open")
	}
	var dev *C.hackrf_device
	var rc C.int
	if h.serial == "" {
		rc = C.hackrf_open(&dev)
	} else {
		cs := C.CString(h.serial)
		defer C.free(unsafe.Pointer(cs))
		rc = C.hackrf_open_by_serial(cs, &dev)
	}
	if rc != C.HACKRF_SUCCESS {
		return fmt.Errorf("hackrf: open failed (serial %q): %s", h.serial, hackrfStrerr(int(rc)))
	}
	if rc := C.hackrf_set_amp_enable(dev, 0); rc != C.HACKRF_SUCCESS {
		C.hackrf_close(dev)
		return fmt.Errorf("hackrf: set_amp_enable failed: %s", hackrfStrerr(int(rc)))
	}
	h.dev = dev
	return nil
}

// SetFrequency tunes the RX. Queued blocks are flushed after the tune
// so a scan step does not feed the pipeline stale pre-retune samples;
// up to one already-in-flight USB transfer may still do so (~6.5 ms at
// 20 MSPS, ~55 ms at 2.4 MSPS).
func (h *HackRF) SetFrequency(hz uint64) error {
	h.mu.Lock()
	defer h.mu.Unlock()
	if h.closed || h.dev == nil {
		return fmt.Errorf("hackrf: device not open")
	}
	if rc := C.hackrf_set_freq(h.dev, C.uint64_t(hz)); rc != C.HACKRF_SUCCESS {
		return fmt.Errorf("hackrf: set_freq(%d Hz) failed: %s", hz, hackrfStrerr(int(rc)))
	}
	h.flushQueueLocked()
	return nil
}

// SetSampleRate sets the ADC rate. Requests above the practical
// 20 MSPS cap (§15.2) are clamped, matching the RTL driver's
// SetSampleRate behavior; the baseband filter follows the rate.
func (h *HackRF) SetSampleRate(hz uint32) error {
	h.mu.Lock()
	defer h.mu.Unlock()
	if h.closed || h.dev == nil {
		return fmt.Errorf("hackrf: device not open")
	}
	if hz == 0 {
		return fmt.Errorf("hackrf: sample rate must be > 0")
	}
	if hz > h.meta.MaxBW {
		hz = h.meta.MaxBW
	}
	if rc := C.hackrf_set_sample_rate(h.dev, C.double(hz)); rc != C.HACKRF_SUCCESS {
		return fmt.Errorf("hackrf: set_sample_rate(%d Hz) failed: %s", hz, hackrfStrerr(int(rc)))
	}
	if rc := C.hackrf_set_baseband_filter_bandwidth(h.dev,
		C.hackrf_compute_baseband_filter_bw(C.uint32_t(hz))); rc != C.HACKRF_SUCCESS {
		return fmt.Errorf("hackrf: set_baseband_filter_bandwidth(%d Hz) failed: %s",
			hz, hackrfStrerr(int(rc)))
	}
	return nil
}

// SetGain applies the total dB figure to the two RX stages (see
// splitHackRFGain). Negative dB is rejected: the HackRF has no auto
// gain mode (§15.4), unlike the RTL driver.
func (h *HackRF) SetGain(db float64) error {
	if db < 0 {
		return fmt.Errorf("hackrf: no auto gain; set 0-102 dB (VGA 0-62 + LNA 0-40, §15.4)")
	}
	lna, vga := splitHackRFGain(db)
	h.mu.Lock()
	defer h.mu.Unlock()
	if h.closed || h.dev == nil {
		return fmt.Errorf("hackrf: device not open")
	}
	if rc := C.hackrf_set_lna_gain(h.dev, C.uint32_t(lna)); rc != C.HACKRF_SUCCESS {
		return fmt.Errorf("hackrf: set_lna_gain(%d) failed: %s", lna, hackrfStrerr(int(rc)))
	}
	if rc := C.hackrf_set_vga_gain(h.dev, C.uint32_t(vga)); rc != C.HACKRF_SUCCESS {
		return fmt.Errorf("hackrf: set_vga_gain(%d) failed: %s", vga, hackrfStrerr(int(rc)))
	}
	return nil
}

// ReadIQ fills buf with full-scale int16 I/Q samples, blocking until
// enough callback blocks have arrived. It must be called from a single
// goroutine (the per-slot IQ read loop, like the RTL driver).
func (h *HackRF) ReadIQ(buf []int16) (int, error) {
	if len(buf) == 0 {
		return 0, nil
	}
	if err := h.ensureStreaming(); err != nil {
		return 0, err
	}
	total := 0
	for total < len(buf) {
		if h.blk == nil {
			select {
			case h.blk = <-h.ready:
			case <-h.done:
				return total, fmt.Errorf("hackrf: device closed")
			case <-time.After(hackRFReadTimeout):
				if h.dead.Load() {
					return total, fmt.Errorf("hackrf: RX stream failed (USB error)")
				}
				return total, fmt.Errorf("hackrf: no data within %s", hackRFReadTimeout)
			}
			h.pos = 0
		}
		n := copy(buf[total:], h.blk[h.pos:])
		total += n
		h.pos += n
		if h.pos >= len(h.blk) {
			h.recycle(h.blk)
			h.blk, h.pos = nil, 0
		}
	}
	// Report queue-overflow drops once per change; otherwise the loss
	// is only visible downstream as §4.3 gaps.
	if d := h.dropped.Load(); d > h.loggedDrops.Load() {
		h.loggedDrops.Store(d)
		log.Printf("[%s] hackrf: dropped %d I/Q pairs (RX queue overflow)",
			h.meta.ID, d)
	}
	return total, nil
}

// Metadata returns the static device description (H2: HasTX false).
func (h *HackRF) Metadata() SDRMetadata { return h.meta }

// Close stops RX and releases the device. Safe to call more than once.
func (h *HackRF) Close() error {
	h.mu.Lock()
	defer h.mu.Unlock()
	if h.closed {
		return nil
	}
	h.closed = true
	if h.dev != nil {
		if h.started {
			// hackrf_stop_rx joins the callback thread; the callback
			// takes no Go locks, so holding mu here is safe.
			C.hackrf_stop_rx(h.dev)
			hackrfOwners.Delete(h.dev)
			h.started = false
		}
		C.hackrf_close(h.dev)
		h.dev = nil
	}
	select {
	case <-h.done:
	default:
		close(h.done)
	}
	return nil
}

// ensureStreaming lazily starts RX on the first read, after startup
// has applied frequency, rate and gain (the libhackrf contract calls
// for hackrf_start_rx after configuration).
func (h *HackRF) ensureStreaming() error {
	h.mu.Lock()
	defer h.mu.Unlock()
	if h.closed {
		return fmt.Errorf("hackrf: device closed")
	}
	if h.dev == nil {
		return fmt.Errorf("hackrf: device not open")
	}
	if h.started {
		return nil
	}
	hackrfOwners.Store(h.dev, h)
	rc := C.hackrf_start_rx(h.dev,
		C.hackrf_sample_block_cb_fn(C.hackrfRXCallback), nil)
	if rc != C.HACKRF_SUCCESS {
		hackrfOwners.Delete(h.dev)
		return fmt.Errorf("hackrf: start_rx failed: %s", hackrfStrerr(int(rc)))
	}
	h.started = true
	return nil
}

// flushQueueLocked recycles queued blocks after a retune. Called with
// h.mu held; channel operations are safe against the RX callback.
func (h *HackRF) flushQueueLocked() {
	for {
		select {
		case b := <-h.ready:
			h.recycle(b)
		default:
			return
		}
	}
}

// recycle returns a block buffer to the freelist (or lets GC take it).
func (h *HackRF) recycle(b []int16) {
	select {
	case h.idle <- b[:cap(b)]:
	default:
	}
}

// hackrfStrerr renders a libhackrf error code as its name.
func hackrfStrerr(rc int) string {
	return C.GoString(C.hackrf_error_name(C.enum_hackrf_error(rc)))
}

// hackrfRXCallback is the libhackrf RX callback (C thread): it widens
// the signed 8-bit stream to full-scale int16 and hands blocks to
// ReadIQ. It must not block and must not call libhackrf functions.
//
//export hackrfRXCallback
func hackrfRXCallback(t *C.hackrf_transfer) C.int {
	v, ok := hackrfOwners.Load(t.device)
	if !ok {
		return 1 // unknown device: stop streaming
	}
	h := v.(*HackRF)
	n := int(t.valid_length)
	if n <= 0 {
		h.dead.Store(true)
		return 1 // stop the stream; ReadIQ surfaces the failure
	}
	if n > int(t.buffer_length) {
		n = int(t.buffer_length)
	}
	n -= n % 2 // keep I/Q pairs
	raw := unsafe.Slice((*byte)(unsafe.Pointer(t.buffer)), n)

	for off := 0; off < n; off += hackRFBlockSamples {
		end := min(off+hackRFBlockSamples, n)
		var b []int16
		select {
		case b = <-h.idle:
		default:
			b = make([]int16, hackRFBlockSamples)
		}
		b = b[:end-off]
		for i := off; i < end; i++ {
			b[i-off] = int16(int8(raw[i])) << 8
		}
		select {
		case h.ready <- b:
		default:
			// Queue full: drop the freshest block (older data stays
			// contiguous) and count the loss in I/Q pairs.
			h.dropped.Add(int64(end-off) / 2)
			h.recycle(b)
		}
	}
	return 0 // continue streaming
}
